"use client"

import React from "react"
import { 
  ArrowLeft, 
  Lock, 
  Database, 
  UserCheck, 
  Mail, 
  Cpu, 
  Trash2, 
  FileCheck,
  ShieldAlert,
  ShoppingBag,
  Scale
} from "lucide-react"
import { useRouter } from "next/navigation"
import Image from "next/image"
import Link from "next/link"
import { motion } from "framer-motion"

export default function PrivacyPolicyPage() {
  const router = useRouter()

  return (
    <div className="min-h-[100svh] bg-[#050505] flex flex-col justify-center items-center p-6 md:p-12 selection:bg-[#E1784F]/30 relative overflow-hidden font-sans">
      
      {/* --- CINEMATIC AMBIANCE --- */}
      <div className="absolute top-[-20%] left-[-10%] w-[500px] md:w-[900px] h-[500px] md:h-[900px] bg-[#E1784F]/10 blur-[120px] md:blur-[250px] rounded-full pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[300px] md:w-[600px] h-[300px] md:h-[600px] bg-[#4DB6AC]/10 blur-[80px] md:blur-[180px] rounded-full pointer-events-none" />
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-[0.03] pointer-events-none" />

      <motion.div 
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-4xl space-y-8 md:space-y-12 relative z-10 my-8"
      >
        
        {/* BRANDING HEADER */}
        <div className="text-center space-y-4 md:space-y-6">
          <motion.div 
            initial={{ scale: 0.8 }}
            animate={{ scale: 1 }}
            className="w-24 h-24 md:w-28 md:h-28 rounded-2xl md:rounded-3xl flex items-center justify-center shadow-[0_20px_40px_rgba(225,120,79,0.2)] mx-auto mb-4 relative group cursor-pointer overflow-hidden"
            onClick={() => router.push("/")}
          >
            <Image
              src="/logo.png"
              alt="AfridamAI Logo"
              width={210}
              height={210}
              className="w-20 h-20 md:w-24 md:h-24 object-contain"
            />
            <div className="absolute inset-0 rounded-2xl md:rounded-3xl border border-white/20 scale-110 opacity-50 group-hover:opacity-100 transition-all duration-500" />
          </motion.div>

          <div className="space-y-3">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-black text-white tracking-tighter uppercase italic leading-none text-center">
              Privacy <span className="text-[#E1784F]">Policy</span>
            </h1>
            <p className="text-white/50 text-xs md:text-sm font-bold uppercase tracking-[0.3em] pt-1">
              Last Updated: September 2026
            </p>
          </div>
        </div>

        {/* ---- PRIVACY POLICY CONTENT CARD --- */}
        <div className="relative">
          <button 
            type="button"
            onClick={() => router.back()}
            className="absolute -top-8 -right-2 md:-top-10 md:-right-8 p-3 md:p-4 text-white/30 hover:text-[#E1784F] hover:scale-110 transition-all z-[100]"
            aria-label="Go back"
          >
            <ArrowLeft className="w-6 h-6 md:w-7 md:h-7" />
          </button>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="space-y-10 bg-white/[0.025] border border-white/10 rounded-3xl p-6 sm:p-10 md:p-12 backdrop-blur-2xl shadow-2xl"
          >
            <p className="text-white/80 text-base md:text-lg leading-relaxed md:leading-loose border-b border-white/10 pb-8 font-normal">
              Welcome to AfriDam AI. By accessing or using our website, AI scan studio, mobile application, marketplace, and clinical access tools, you explicitly agree to the Privacy Policy and Terms of Service detailed below.
            </p>

            {/* PART I */}
            <h2 className="text-white font-black uppercase text-sm md:text-base tracking-[0.2em] border-b border-white/10 pb-3">
              PART I: MEDICAL & SERVICE DISCLAIMER (CRITICAL PRECAUTIONS)
            </h2>

            {/* Section 1: AI Output & Non-Diagnostic Disclaimer */}
            <div className="space-y-4">
              <div className="flex items-center gap-3.5">
                <ShieldAlert className="text-[#E1784F] shrink-0" size={24} />
                <h2 className="text-[#E1784F] font-black uppercase text-base md:text-lg tracking-[0.18em]">
                  1. AI Output & Non-Diagnostic Disclaimer
                </h2>
              </div>
              <ul className="text-white/70 text-sm md:text-base leading-relaxed pl-9 space-y-3">
                <li>• <strong className="text-white font-semibold">Aesthetic & Wellness Guidance Only:</strong> The outputs generated by the AfriDam AI platform—including skin scores, condition tags, bounding boxes, parameter ratings, and product recommendations—are intended solely for informational, beauty, aesthetic, and educational purposes.</li>
                <li>• <strong className="text-white font-semibold">Not a Medical Device or Primary Diagnosis:</strong> AfriDam AI is an artificial intelligence decision-support and aesthetic profiling tool. It is NOT a licensed medical device, nor does it provide definitive clinical diagnosis, treatment, or medical prescriptions.</li>
                <li>• <strong className="text-white font-semibold">Mandatory Professional Verification:</strong> AI predictions can occasionally produce errors, false positives, or incomplete assessments. You MUST NOT rely solely on the AI scan outputs for medical decision-making. Users are strongly advised to verify all AI evaluations by consulting a board-certified dermatologist or licensed medical clinician through our platform&apos;s tele-consultation service or an independent medical facility.</li>
                <li>• <strong className="text-white font-semibold">Emergency Situations:</strong> If you experience severe medical symptoms, acute allergic reactions, sudden skin lesions, or painful infections, do NOT rely on AfriDam AI. Seek immediate in-person emergency medical care from a qualified hospital or practitioner.</li>
              </ul>
            </div>

            {/* Section 2: Third-Party Marketplace */}
            <div className="space-y-4">
              <div className="flex items-center gap-3.5">
                <ShoppingBag className="text-[#E1784F] shrink-0" size={24} />
                <h2 className="text-[#E1784F] font-black uppercase text-base md:text-lg tracking-[0.18em]">
                  2. Third-Party Marketplace, Vendors & Order Fulfillment Disclaimer
                </h2>
              </div>
              <ul className="text-white/70 text-sm md:text-base leading-relaxed pl-9 space-y-3">
                <li>• <strong className="text-white font-semibold">Affiliate & Vendor Partnerships:</strong> AfriDam AI partners with third-party e-commerce platforms, retail chains, and skincare brand manufacturers (including platforms such as Jumia, pharmacy vendors, and direct brand suppliers) to enable access to recommended products.</li>
                <li>• <strong className="text-white font-semibold">No Direct Sales or Inventory:</strong> AfriDam AI does not manufacture, warehouse, store, pack, or directly ship physical skincare products listed on the marketplace or linked via scan recommendations.</li>
                <li>• <strong className="text-white font-semibold">Fulfillment & Shipping Liability:</strong> All transactions, product deliveries, shipping timelines, package tracking, returns, exchanges, and product quality guarantees are the sole responsibility of the respective third-party vendor or merchant. AfriDam AI expressly disclaims any liability for delayed deliveries, damaged items, lost packages, adverse skin reactions to third-party formulations, or merchant disputes.</li>
              </ul>
            </div>

            {/* PART II */}
            <h2 className="text-white font-black uppercase text-sm md:text-base tracking-[0.2em] border-b border-white/10 pb-3">
              PART II: PRIVACY POLICY & CLINICAL DATA GOVERNANCE
            </h2>

            {/* Section 3: Information We Collect */}
            <div className="space-y-4">
              <div className="flex items-center gap-3.5">
                <Database className="text-[#E1784F] shrink-0" size={24} />
                <h2 className="text-[#E1784F] font-black uppercase text-base md:text-lg tracking-[0.18em]">
                  3. Information We Collect
                </h2>
              </div>
              <p className="text-white/70 text-sm md:text-base leading-relaxed pl-9">
                To deliver our AI skin profiling and marketplace experience, we collect:
              </p>
              <ul className="text-white/70 text-sm md:text-base leading-relaxed pl-9 space-y-3">
                <li>• <strong className="text-white font-semibold">Personal & Account Identifiers:</strong> Name, email address, phone number, age, gender, and login credentials.</li>
                <li>• <strong className="text-white font-semibold">Biometric & Image Data:</strong> Facial and localized skin photos uploaded or captured directly via your camera for real-time AI scan evaluation.</li>
                <li>• <strong className="text-white font-semibold">Skin Profile & Survey Data:</strong> Self-reported skin histories, sensitivities, concern ratings, barrier metrics, and product preferences.</li>
                <li>• <strong className="text-white font-semibold">Transaction & Billing Data:</strong> Order histories and shipping addresses. Payment processing is handled by PCI-DSS certified payment gateways (e.g., Paystack). Raw credit/debit card details are never stored or accessible on our servers.</li>
                <li>• <strong className="text-white font-semibold">Technical & Usage Metadata:</strong> Device type, operating system, IP address, browser fingerprint, and cookie interaction data.</li>
              </ul>
            </div>

            {/* Section 4: How We Use Data */}
            <div className="space-y-4">
              <div className="flex items-center gap-3.5">
                <Cpu className="text-[#E1784F] shrink-0" size={24} />
                <h2 className="text-[#E1784F] font-black uppercase text-base md:text-lg tracking-[0.18em]">
                  4. How We Use Data & B2B AI Model Training
                </h2>
              </div>
              <p className="text-white/70 text-sm md:text-base leading-relaxed pl-9">
                Your data powers our aesthetic engine and global health equity initiatives:
              </p>
              <ul className="text-white/70 text-sm md:text-base leading-relaxed pl-9 space-y-3">
                <li>• <strong className="text-white font-semibold">Primary AI Profiling:</strong> Computer vision algorithms analyze skin photos to measure visual skin metrics, suggest product matches, and generate aesthetic insights.</li>
                <li>• <strong className="text-white font-semibold">Dark Skin Model Optimization & Research Partnerships:</strong> Fully anonymized and de-identified skin imagery (stripped of all personal identifying information, names, emails, and direct identifiers) is processed to continuously train, refine, and validate our AI algorithms specifically for dark skin biomarkers (Fitzpatrick Phototypes IV–VI).</li>
                <li>• <strong className="text-white font-semibold">Global B2B Data Licensing:</strong> To advance global dermatology AI and eliminate demographic bias, AfriDam AI may share or license fully de-identified, non-reidentifiable clinical datasets and coordinate metadata with verified healthcare research institutions, AI developers, and clinical partners under strict Data Use Agreements (DUAs).</li>
                <li>• <strong className="text-white font-semibold">Virtual Consultations:</strong> Scan reports and image histories are shared exclusively with board-certified dermatologists or tele-doctors only when you explicitly book a virtual consultation on our platform.</li>
              </ul>
            </div>

            {/* Section 5: Data Protection */}
            <div className="space-y-4">
              <div className="flex items-center gap-3.5">
                <UserCheck className="text-[#E1784F] shrink-0" size={24} />
                <h2 className="text-[#E1784F] font-black uppercase text-base md:text-lg tracking-[0.18em]">
                  5. Data Protection, Anonymization & Strict Non-Sale of Personal Data
                </h2>
              </div>
              <ul className="text-white/70 text-sm md:text-base leading-relaxed pl-9 space-y-3">
                <li>• <strong className="text-white font-bold  decoration-[#E1784F]">Strict Non-Sale of PII:</strong> We NEVER sell, rent, lease, or trade your Personally Identifiable Information (PII), contact details, or unanonymized personal scan logs to advertisers, marketers, or commercial data brokers.</li>
                <li>• <strong className="text-white font-semibold">Anonymization Standard:</strong> Any image data or coordinate metadata utilized for AI training or research licensing is subjected to rigorous de-identification standards (removing identity contexts like: names, contact numbers, and location identifiers) so that no individual user can ever be identified or re-identified.</li>
              </ul>
            </div>

            {/* Section 6: User Rights
